# -*- sh -*-
# shellcheck shell=bash

# bashrc
# Linked by ~/.bashrc

# Note: the shebang is ignored. It is only there to help editors and
# linters. resource files are not executed. They are sourced into the shell
# that calls them, to which any line with a # is a comment.

# shellcheck disable=SC1090 #https://github.com/koalaman/shellcheck/wiki/SC1090
# shellcheck disable=SC1091 #https://github.com/koalaman/shellcheck/wiki/SC1091

## How to plug in (monkeypatch) set -x, VERBOSE_PROFILE, etc, if needed. Use
## the "monkeypatch" program to manage this file.
[[ -x "${TILDAE}/bashrc.monkeypatch" ]] && . "${TILDAE}/bashrc.monkeypatch"

"$HOME/personal/bin/monkeytell" \
    "$VERBOSE_RC" "${TILDAE}/.bashrc" 'start'

# User specific environment and startup programs. The main one is the personal
# one, which is '~/.bashrc.${USER}'. All the rest ( ~/.bashrc.${USER}*) will
# sort after the first one, so make sure they name-sort in the order you want
# them to be sourced.
for b in ~/.bashrc."${USER}"*; do
    [[ -e "${b}" ]] || continue # Make sure the glob isn't empty
    if [[ -e "${b}.skip" ]]; then
        echo "Skipping ${b} because ${b}.skip found" >&2
    else
        var=BASHRC_SKIP_$(basename "${b}" | sed 's/\./_/g')
        var=${var^^}
        val="$(eval echo \$"$var")"
        if [[ -n "$val" ]]; then
            echo "Skipping ${b} because $var exists (value $val)" >&2
        else
            . "${b}"
        fi
    fi
done

"$HOME/personal/bin/monkeytell" \
    "$VERBOSE_RC" "${TILDAE}/bashrc" 'end'

RAN_BASHRC="PID:$$ at $(date)"
export RAN_BASHRC
