#!/usr/bin/env bash

# dotfilesbootstrap
dotdir="$(realpath .)"
personaldir="$(dirname "$dotdir")"

declare -a funclist
funclist=()
funclist+=(safe_func_export) # Directly used here

# Directly used in makesymlink
funclist+=(ajoin aplit apush apop aunshift ashift)

for func in "${funclist[@]}"
do
    # shellcheck disable=SC1090
    . "$dotdir/../functions/$func"
    safe_func_export "$func"
done

export PATH="$personaldir/bin:$PATH"
