#!/usr/bin/env bash

# dotfilesbootstrap

dotdir="$(realpath .)"
personaldir="$(dirname "$dotdir")"
# shellcheck disable=SC1090
. "$dotdir/dotfiles.env"

declare -a funclist
funclist+=(safe_func_export gitcheck_dotfiles _save-dotfile-entry)
funclist+=(syncdotfiles makesymlinks makepstree asplit)
funclist+=(asplit-to-array asplit-to-stdout ashift asplice)
for func in "${funclist[@]}"
do
    # shellcheck disable=SC1090
    . "$dotdir/../functions/$func"
    safe_func_export "$func"
done

export PATH="$personaldir/bin:$PATH"
