#!/usr/bin/env bash

# <Function Class: cd>
# <Function Justification: env mod>

_dirlist_select ()
{
    local PS3="Choose by number, - for prior, q to quit: "
    local d
    select d in "$@"
    do
        if [ -n "$d" ]
        then
            d="$(echo "$d" | sed "s|$DIRLIST_PWD_INDIC||" | sed "s|\\~|$HOME|")"
            if [ -d "$d" ]
            then
                builtin cd "$d"
                break
            else
                stderrcho "$d no longer exists"
            fi
        else
            local reply
            reply=$(echo "$REPLY" | tr '[:upper:]' '[:lower:]')
            if [ "$reply" = 'q' ]
            then
                return
            elif [ "$reply" = '-' ]
            then
                builtin cd -
                return
            else
                echo "'$REPLY' is an invalid choice"
            fi
        fi
    done
}
