#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: env mod>

_git-cd-return ()
{
    local tgt
    tgt=$(apop GITFUNCS_OLDPWDS) ## We pop no matter what so bad dirs are
                                 ## cleared from the stack and we don't get
                                 ## stuck on them.
    # shellcheck disable=SC2164
    [ -n "$tgt" ] && builtin cd "$tgt"
    return $?
}
