#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: env mod>

_git-cd-unwind ()
{
    local tgt=$(ashift GITFUNCS_OLDPWDS)
    if [ -n "$tgt" ]
    then
        ## We pop no matter what so bad dirs are cleared from the stack and we
        ## don't get stuck on them.
        aclear GITFUNCS_OLDPWDS && builtin cd $tgt
    fi
    return $?
}
