#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: env mod>

_git-cd-to ()
{
    local tgt
    tgt=$(realpath "$1")
    local src
    src=${PWD}
    builtin cd "$tgt" && GITFUNCS_OLDPWDS+=("$src") ## Push only if we can get
                                                    ## to the target
    return $?

}
