#!/usr/bin/env bash

# <Function Class: bashhash>
# <Function Justification: env access>

_listkv ()
{

    declare -n array_alias="$1"
    declare i
    for i in "${!array_alias[@]}"; do
        printf "%s %s\\n" "$i" "${array_alias[$i]}"
    done
    return 0
}
