#!/usr/bin/env bash

# <Function Class: dotfiles>
# <Function Justification: env mod>

_save-dotfile-entry ()
{
    local key=$1
    local link=$2
    local tmp=${DOTFILES_MANIFEST}.$$

    cp -f $DOTFILES_MANIFEST $tmp
    link=$(echo $link | sed "s|${TILDAE:-$HOME}|\${TILDAE:-$HOME}|")
    echo "dotfiles[$key]=$link" >> $tmp
    mv $tmp $DOTFILES_MANIFEST
    . $DOTFILES_MANIFEST
}
