#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

aclear ()
{
    ##@@ none||none||aclear||Remove all the elements from the array named in arg1.

    declare -n array_alias="$1";shift
    array_alias=()
    return $(true)
}
