#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

acopy ()
{
    ##@@ none||none||acopy||Copy all the values from the array named in arg2 to the array named in arg1. arg1 is not cleared first. Sparse indicies are maintined.

    declare -n array_alias_tgt="$1";shift;
    declare -n array_alias_src="$1";shift;
    for i in ${!array_alias_src[@]}
    do
        array_alias_tgt[$i] = "${array_alias_src[$i]}"
    done
    return $(true)
}
