#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

acount ()
{
    ##@@ none||none||acount||Print the number of elements in the array named in arg1 to stdout. This is not necessarily the value of the last index, due to sparseness.

    declare -n array_alias="$1"
    echo ${#array_alias[@]}
    return 0
}
