#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

aeach ()
{
    ##@@ none||none||aeach||Print all the index values and values of the array named in arg1 to stdout. Each index and value is separated by a space. Each pair is printed on a separate line.

    _listkv "$1"
    return $?
}
