#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

ajoin()
{
    ##@@ none||none||ajoin||Print one string that joins arg2, arg3, etc, separated by arg1

    local IFS="$1"; shift; echo "$*";return $?
}
