#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

apop ()
{
    declare -n arr="$1";shift
    ((${#arr[@]} == 0)) && return
    echo "${arr[-1]}"
    unset "arr[-1]"
}
