#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

apush ()
{
    ##@@ none||none||apush||Append arg2, arg3, etc.. to the end of the array named in arg1.

    local array_name="$1";shift
    asplice "$array_name" "$(acount "$array_name")" 0 "$@"
    return $?
}
