#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

ashift ()
{
    declare q=0; if [ "$1" == "-q" ]; then q=1; shift; fi
    declare -n arr;arr="$1";shift
    ((!q)) && echo "${arr[0]}"
    unset "arr[0]"
    arr=("${arr[@]:1}")
}
