#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

asplit_to_array ()
{
    ##@@ none||none||asplit_to_array||Call asplit-to-array instead.

    asplit-to-array "$@"
}
