#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

asplit-to-array ()
{
    declare -n array_alias="$1"
    ## 'local' not needed for IFS here since it's all one command.
    # shellcheck disable=SC2034 ## array_alias is used externally
    IFS="$2" read -r -a array_alias <<< "$3"
    status=$?
    return $status
}
