#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

asplice ()
{
    local print_removed=0
    [ "$1" = '--removed' ] && print_removed=1 && shift

    ## The array to modify
    declare -n arr="$1"; shift

    ## The index into the array indicating the first element to remove. If the
    ## # to remove is 0, then any additions just start after this element.
    local offset=0; [ -n "$1" ] && offset=$1 && shift
    (( offset < 0 )) && ((offset=${#arr[@]}+offset))

    ## The number of elements to remove.
    local aal=${#arr[@]}
    local length=$((aal-offset)); [ -n "$1" ] && length=$1 && shift

    ## The removed elements, if desired.
    ((print_removed)) && echo "${arr[@]:$offset:$length}"

    ## The modified array: The retained elements to the left, any new elements
    ## replacing the removed elements and the retained elements to the right.
    arr=("${arr[@]:0:$((offset))}" "$@" "${arr[@]:$((length+offset))}")

    return 0
}
