#!/usr/bin/env bash

# <Function Class: bash arrays>
# <Function Justification: env mod>

aunshift ()
{
    ##@@ none||none||apush||Prepend arg2, arg3, etc.. to the beginning of the array named in arg1.

    local array_name="$1";shift
    asplice $array_name 0 0 "$@"
    return $?
}
