#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: none>

bash_current_version_compare()
{
    ##@@ none||none||bash_current_version_compare||Compare current bash shell's version against the version in arg1. Return 255, 0, 1 accordingly (because -1 gets foobared in shell).

    local other_bash_version
    ## Can't use asplit here - catch 22
    IFS='.' read -r -a other_bash_version <<< "$1"

    local i
    for i in 0 1 2 3
    do
        [ -z "${other_bash_version[$i]}" ] && other_bash_version[$i]=0
        if (( ${BASH_VERSINFO[$i]} < ${other_bash_version[$i]} ))
        then
            echo 255
        fi
        if (( ${BASH_VERSINFO[$i]} > ${other_bash_version[$i]} ))
        then
            echo 1
        fi
    done
    return 0
}
