#!/usr/bin/env bash

# <Function Class: cd>
# <Function Justification: env mod>

cleandirlist ()
{
    ## Remove the current dir marker
    [ -n "$DIRLIST" ] && \
	    DIRLIST=$(echo "${DIRLIST}" | sed "s|$DIRLIST_PWD_INDIC||g")
}
