#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: none>

comment-stream ()
{

    local comment="$1";shift
    IFS="$(printf '\n')"

    while read -r line
    do
        echo "${comment}$line"
    done
    return 0
}
