#!/usr/bin/env bash

# <Function Class: cd>
# <Function Justification: change cwd>

# DO NOT REPLACE WITH AN ALIAS. The alias doesn't make it to subshells.

ecd ()
{
    dirlist "$@"
}
autotrack ecd "$0"
