#!/usr/bin/env bash

# <Function Class: utils>
# <Function Justification: speed, resources>

false ()
{
    # The only place we hardcode 1 - do not want to call 'false' as that starts
    # up another process.
    return 1
}

:<<'__PODUSAGE__'
=head1 NAME

false - a function version of 'false'

=head1 SYNOPSIS

 false; return

=head1 DESCRIPTION

Sets $? to a false value without starting up another process.

=cut

__PODUSAGE__
