#!/usr/bin/env bash

# <Function Class: utils>
# <Function Justification: speed, resources>

ftrue ()
{
    # The only place we hardcode 0 - do not want to call 'true' as that starts
    # up another process.
    return 0
}

:<<'__PODUSAGE__'
=head1 NAME

ftrue - a function version of 'true'

=head1 SYNOPSIS

 ftrue; return $?

=head1 DESCRIPTION

Sets $? to a true value without starting up another process.

=cut

__PODUSAGE__
