#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: env access>

func-name-spoof ()
{

    local spoofing=$(false)
    local iam=${FUNCNAME[1]}
    if [ -n "${FUNCNAME[2]}" ] && \
           [ ! "${FUNCNAME[2]}" = 'source' ] && \
           [ ! "${FUNCNAME[2]}" = 'main' ]
    then
        iam="${FUNCNAME[2]}"
        spoofing=$(true)
    fi
    echo $iam
    return $spoofing
}
