#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: calls cmd-echo>

func-yesno ()
{
    local prompt_text
    prompt_text="$(cmd-echo -n "$1")"
    shift
    yesno "$prompt_text" "$@"
}
