#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: calls cmd-echo>

func-pick ()
{
    local prompt_text
    prompt_text="$(cmd-echo -n '')$1"
    shift
    pick "$prompt_text" "$@"
}
