#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-cat-cl ()
{
    ##@@ 0001||group||git-cat-cl||'cat' the ChangeLog in the git root

    local cl=$(git-root)/$GITFUNCS_CHANGELOG_NAME
    [ -r $cl ] && cat $cl && return $OK
    echo "$cl not found."
    return $NOT_OK
}
