#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-cat-cl ()
{
    local cl
    cl="$(git root)/$GITFUNCS_CHANGELOG_NAME"
    [ -r "$cl" ] && cat "$cl" && return 0
    echo "$cl not found."
    return 1
}
