#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-sync-with-remote-usage ()
{
    echo "Usage: $1 --branch otherBranch [--remote remote] [--confirm]"
    echo "       Rebase your branch from another remote branch."
    echo "       'remote' defaults to 'origin'."
}
