#!/usr/bin/env bash

# <Function Class: gitfuncs.github>
# <Function Justification: change cwd>

git-clone-github ()
{
    [ -z "$1" ] && func-usage && return 1

    git-clone --proto github "$@"
    return $?
}
