#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-merge-write-usage ()
{
    echo "Usage: git-merge-write sha githost tgtorg tgtrepo tgtbranch srcorg srcrepo srcbranch [merged-by]"
}
