#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-worktree-root ()
{
    ##@@ 0001||group||git-worktree-root||print the master root where the wt dir is

    local i
    local status=0
    local wtr=$(git worktree list | \
                                  grep '\[master\]' | \
                                  sed 's/....... \[master\]//' | \
                                  sed 's/\s\{1,\}$//')
    for i in ${PIPESTATUS[@]}
    do
        ((i>status)) && status=$i
    done
    ((status)) && return $status
    if [ -n "$wtr" ]
    then
        echo $wtr
        return $OK
    else
        echo
        return $NOT_OK
    fi
}
