#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-diff-two-repos-on-disk-usage ()
{
    cat<<EOUSAGE
Usage: git-diff-two-repos-on-disk [src] tgt
       git-diff-two-repos-on-disk [-h|-help]

       Compare two repos on disk. If only one repo is specified,
       'src' is taken as the current directory, which should be
       a repo root.
EOUSAGE
}
