#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-hold-find ()
{
    ##@@ 0001||group||git-hold-find||show all entries in the git hold stash
    find "$(git root)/.githold" -type f "$@" 2>/dev/null
}
