#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-push-hook ()
{
    ##@@ 0001||group||git-push-hook||

    git-hook-pushpull-guts $(_git-go-get -m | grep -v ".git_template" )
}
