#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-delete-repo-usage ()
{
    local cmd=$1;shift
    local protocol=$1
    local protocolarg=$1
    if [ -z "$protocol" ]
    then
        protocol='protocol'
        protocolarg='protocol'
    else
        protocolarg=''
    fi

    cat <<EOUSAGE
Usage: $cmd $protocolarg namespace repo
       Whacks local repo $gitfuncs_gitroot/$protocol/namespace/repo.
       Asks about corresponding remote.
EOUSAGE
    return $OK
}
