#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-diff-to-checkpoint ()
{
    local oldid
    oldid="$(grep "$(git root).git-pull-checkpoint|" head -1 | sed 's/commit//')"
    local newid
    newid="$(git log -1 | head -1 | sed 's/commit//')"
    git diff "$oldid" "$newid"
}
