#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-st-ext-all ()
{
    ##@@ 0001||group||git-st-ext||Read all notes about repo current statuses

    for i in $(git-go --listfull)
    do
        ( builtin cd $i
          local s=$(git-st-ext)
          [ -n "$s" ] && echo $i - $s
        )
    done
}
