#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-branch-info-pull-request ()
{
    local branch
    branch=$(git rev-parse --abbrev-ref HEAD)
    local OPTSARGS
    OPTSARGS=$(getoptp -o b: --long branch: -n "${FUNCNAME[@]}" -- "$@")
    local status=$?
    ((status != 0)) && func-usage && return $status

    eval set -- "$OPTSARGS"
    while true
    do
        case "$1" in
            --branch|-b) branch=$2; shift; shift;;
            --) shift; break ;; ## end of opts, remaining $*, if any, are args
            *) echo "Internal error!"; func-usage; return 1 ;;
        esac
    done

    git-branch-info --branch "$branch" pull-request "$1"
}
