#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-pull ()
{
    local opt_t=0
    local OPTSARGS
    OPTSARGS=$(getoptp -o th --long timestamp,help -n "${FUNCNAME[0]}" -- "$@")
    local status=$?
    ((status != 0)) && func-usage && return $status

    eval set -- "$OPTSARGS"
    while true
    do
        case "$1" in
            -t|--timestamp) opt_t=1; shift ;;
            -h|--help) func-usage; return 0 ;;
            --) shift; break ;; ## end of opts, remaining $*, if any, are args
            *) echo "Internal error!"; func-usage; return 1 ;;
        esac
    done

    local oldsha
    oldsha=$(git-log-grab-sha -1)
    git pull
    if ((opt_t))
    then
        func-echo "Setting timestamps..."
        git-retimestamp
        func-echo Done
    fi
    git-log-shas-range -f "pre-pull:" "$oldsha" "$(git-log-grab-sha -1)"
}
