#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-hook-find-hook-dir ()
{
    local dotgit
    dotgit=$(git-find-git-dir)
    if [ -n "$dotgit" ] && [ -d "$dotgit/hooks" ]
    then
        echo "$dotgit/hooks"
        return 0
    else
        echo
        return 1
    fi
}
