#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-get-current-branch ()
{
    ##@@ 0001||group||git-get-current-branch||

    ( if [ -n "$1" ]
      then
          ## dirlist, not builtin cd, to take advantage this cd enhancement
          dirlist $1
      fi
      git symbolic-ref HEAD | cut -d/ -f3-
    )
}
