#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-hold ()
{
    local holdroot
    holdroot=$(git root)/.githold
    local -a holdthese
    holdthese=("$@")
    if [ -z "${holdthese[0]}" ]
    then
        readarray -t holdthese < <(git-is-mod)
    fi

    local retstat=0
    for orig in "${holdthese[@]}"
    do
        local hold="$holdroot/$orig"

        if [ -e "$hold" ]
        then
            ((retstat+=1))
            func-echo "Cannot hold $orig - hold version already exists:"
            ls -la "$hold"
        else
            mkdir -p "$(dirname "$hold")"
            if cp -v "$orig" "$hold";
            then
                git checkout "$orig"
            else
                ((retstat+=1))
                func-echo "Cannot hold $orig - copy failed"
            fi
        fi
        echo
    done
    return $retstat
}
