#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-hold-clean ()
{
    ##@@ 0001||group||git-hold-clean||remove all entries in the git hold stash
    rm -rf $(git-root)/.githold
}
