#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-restore ()
{
    ##@@ 0001||group||git-restore||

    echo "Use 'git log' to find the id (sha) of the revision that contains"
    echo "the prior version of the file you want to revert to."
    echo "Then execute 'git checkout sha the/file/to/revert'."
}
