#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-merge-pull-request-usage ()
{
    local cmd=$1;shift
    local githost=$1
    local githostarg=$1
    if [ -z "$githost" ]
    then
        githost='githost'
        githostarg='githost'
    else
        githostarg=''
    fi

    cat <<EOUSAGE

Usage: $cmd $githostarg tgtnamespace/tgtrepo/tgtbranch srcnamespace/srcrepo/srcbranch
       $cmd $githostarg tgtnamespace/tgtrepo/tgtbranch srcnamespace:srcbranch
       $cmd $githostarg tgtnamespace/tgtrepo/tgtbranch srcbranch
       $cmd $githostarg --upstream srcbranch
       $cmd $githostarg --upstream
       $cmd $githostarg

       Other options:
           --verbose - prints blow-by-blow action descriptions
           --keep    - unconditionally keep (do not ask about)
                       the target clone

       Merge the branch from the 'src' into the 'tgt'.

       The typical usage looks like

           $cmd $githostarg dkpg/bulddeb mybranch

       In this case:

           - the source namespace defaults to your username
           - the source repo defaults to the target repo name
           - the target branch is 'master'

       Merging someone else's branch looks like

           $cmd $githostarg dpkg/builddeb/ user//theirbranch

       As a cut 'n paste convenience, we also accept

           $cmd $githostarg dpkg/builddeb/ user:theirbranch

       Furthermore, if your local repo that has the objects to merge is clone
       of a fork of the canonical repo, i.e. you are using the 'triangle'
       workflow, you can replace the target spec with --upstream. In this case,
       the target namespace and repo is the result of the command

           git config --get remote.upstream.url

       If the source is not specified, we assume the current branch.

       If the target is not specified, we assume --upstream.

       The use of --upstream and the current branch assumes you are in the
       branch that you have just pushed up to be merged.

EOUSAGE

}
