#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-hold-diff ()
{

    ##@@ 0001||group||git-hold-diff||show difference between entries in the git hold stash and the repo
    local pager='less -RE'
    local -a diffargs
    local OPTSARGS
    OPTSARGS=$(getoptp -o w --long nopager -n "${FUNCNAME[0]}" -- "$@")
    status=$?
    ((status != 0)) && func-usage && return $status
    eval set -- "$OPTSARGS"
    while true
    do
        case "$1" in
            -w) diffargs+=("-w"); shift;;
            --nopager) pager='cat'; shift;;
            --) shift; break ;; ## end of opts, remaining $*, if any, are args
            *) echo "Internal error!"; func-usage; return 1 ;;
        esac
    done

    local -a diffthese
    diffthese=("$@")
    if [ -z "${diffthese[0]}" ]
    then
        diffthese=("$(git-hold-find)")
    else
        local i
        for i in "$@"
        do
            local -a j
            readarray -t j < <(git-hold-find | grep "$i")
            if [ -z "${j[0]}" ]
            then
                func-echo "Cannot find $i to diff"
            else
                diffthese+=("${j[@]}")
            fi
        done
    fi

    for hold in "${diffthese[@]}"
    do
        local orig
        orig=${hold//.githold/|}
        colordiff -u "${diffargs[@]}" "$orig" "$hold"
        echo
    done  | $pager

    return 0
}
