#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-check-hook ()
{
    local hook_dir
    hook_dir=$(git-hook-find-hook-dir)
    if [ -z "$hook_dir" ] || [ ! -d "$hook_dir" ]
    then
        echo "Cannot find hook directory"
        return 1
    fi
    local i
    # shellcheck disable=SC2010 # We want to filter the filenames, not search the files
    for i in $(ls "${hook_dir}/*" | grep -v '.sample' | grep -v "$GITFUNCS_CHANGELOG_NAME")
    do
        if [ ! -x "$i" ]
        then
            echo "INFO: git hook $i is not executable. Making it so."
            chmod a+x "$i"
        fi
    done
    return 0
}
