#!/usr/bin/env bash

# <Function Class: gitfuncs.github>
# <Function Justification: none>

git-delete-repo-github ()
{
    [ -z "$1" ] && func-usage && return 1
    git-delete-repo github "$@"
    return $?
}
