#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-pull-usage ()
{
    cat <<EOUSAGE
Usage: git-pull [-t]
       Does a git pull, followed by a descriptive git status.
       -t resets the timestamps on the pulled files
          to their original commit times
EOUSAGE
}
