#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-to-stdout-usage ()
{
    echo 'Usage: git-to-stdout [--file] uuid objectname [objectname...]'
    echo '       From the version specified by "uuid" print the objects'
    echo '       requested to stdout. "objectname" must be fully quailifed'
    echo '       from the repo root, not current directory. If --file'
    echo '       is specified, then write to file to objectname.uuid instead'
}
