#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-merge-write ()
{
    ##@@ 0001||group||git-merge-write||

    [ -z "$1" ] && \
        echo "Usage: git-merge-write sha githost tgtorg tgtrepo tgtbranch srcorg srcrepo srcbranch [merged-by]" && \
        return 1

    local sha=$1;shift
    local githost=$1;shift;
    local tgt=("$1" "$2" "$3");shift;shift;shift
    local src=("$1" "$2" "$3");shift;shift;shift
    local merged_by
    merged_by=$(id -n -u)
    [ -n "$1" ] && merged_by=$1 && shift;
    local merge_audit_value
    merge_audit_value="${sha}@$(date +%Y_%m_%d-%H_%M_%S)@$merged_by"
    src[2]=$(echo "${src[2]}" | sed 's/\//---/g')
    tgt[2]=$(echo "${tgt[2]}" | sed 's/\//---/g')
    local merge_audit_key_by_tgt="merge-pr-by-tgt.${githost}--${tgt[0]}--${tgt[1]}--${tgt[2]}.${githost}--${src[0]}--${src[1]}--${src[2]}"
    git config -f "${TILDAE:-$HOME}/.gitconfig.merge_audit" "$merge_audit_key_by_tgt" "$merge_audit_value"

    local merge_audit_key_by_src="merge-pr-by-src.${githost}--${src[0]}--${src[1]}--${src[2]}.${githost}--${tgt[0]}--${tgt[1]}--${tgt[2]}"
    git config -f "${TILDAE:-$HOME}/.gitconfig.merge_audit" "$merge_audit_key_by_src" "$merge_audit_value"
}
