#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-rename-branch ()
{
    if (($#!=2))
    then
        func-usage
        return 1
    fi

    local old_branch=$1; shift
    local new_branch=$1; shift
    if (($#))
    then
        func-usage
        echo "       argument(s) '$*' are illegal"
        return 1
    fi

    # Rename branch locally.
    echo "git branch -m $old_branch $new_branch ..."
    git branch -m "$old_branch" "$new_branch"        || return $?

    # Delete the old branch. DON'T DO THIS IF YOU HAVE AN OPEN PULL REQUEST!!!
    echo "git push origin --delete $old_branch ..."
    git push origin --delete "$old_branch"         || return $?

    # Push the new branch, set local branch to track the new remote.
    echo "git push --set-upstream origin $new_branch"
    git push --set-upstream origin "$new_branch"
    return $?
}
