#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-find-last-existed ()
{
    ##@@ 0001||group||git-find-last-existed||The revision before which the given file was deleted.

    git rev-list -n 1 $(git-find-deleted "$1")^ -- "$1"
}
