#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-update-this-hook ()
{
    ##@@ 0001||group||git-update-hook||

    declare -a hooks
    hooks=("$@")
    if ((${hooks[@]}==0))
    then
        local filename
        # shellcheck disable=SC2154 #global non-all cap
        for filename in ${gitfuncs_githook_dir}/*
        do
            if [[ $filename =~ ^(README.md|$GITFUNCS_CHANGELOG_NAME)$ ]]
            then
                continue
            fi
            hooks+=("$filename")
        done
    else
        local h
        declare -a newh
        for h in "${hooks[@]}"
        do
            newh+=("${gitfuncs_githook_dir}/$h")
        done
        hooks=("${newh[@]}")
    fi
    local REPOS REPO
    REPOS=$(_git-go-get -m)
    for REPO in $REPOS
    do
        for h in "${hooks[@]}"
        do
           local hookdir
           hookdir="${TILDAE:-$HOME}/$(git-strip-repo "$REPO")/.git/hooks"
           if [ -e "$hookdir/$(basename "$h")" ]
           then
               cp -v "$h" "$hookdir"
           fi
        done
    done
}
