#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-worktree-root ()
{
    local i
    local status=0
    local wtr
    wtr=$(git worktree list | \
              grep '\[master\]' | \
              sed 's/....... \[master\]//' | \
              sed 's/\s\{1,\}$//')
    for i in "${PIPESTATUS[@]}"
    do
        ((i>status)) && status=$i
    done
    ((status)) && return "$status"
    if [ -n "$wtr" ]
    then
        echo "$wtr"
        return 0
    else
        echo
        return 1
    fi
}
