#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: env mod>

git-wrapper ()
{
    declare g="$PERSONALBIN/git"
    declare a="$1"

    if [[ "$a" =~ toggle ]] || [ -z "$a" ]
    then
        [ -x "$g" ] && a=off || a=on
    fi

    if [[ "$a" =~ off ]]
    then
        chmod a-x "$g"
    else
        chmod a+x "$g"
    fi
    hash -r
    echo "'git' is now $(which git)"
}
