#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-revert ()
{
    ##@@ 0001||group||git-revert||revert to the latest unmodified version on the current branch, losing any modifications.
    git checkout -- "$@"
}
