#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-get-stash-count ()
{
    ##@@ 0001||group||git-get-stash-count||
    local no0=0; [ "$1" = '-no0' ] && no0=1 && shift;
    local pre=$1;shift
    local post=$1;shift
    git-in-a-repo
    if [ "$?" = $TRUE ]
    then
        local c=$(git stash list 2>/dev/null | wc -l)
        ((c==0)) && ((no0)) && return
        echo "${pre}${c}${post}"
    fi
}
