#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-set-triangle-usage ()
{
    local cmd=$1;shift
    local githost=$1
    if [ -z "$githost" ]
    then
        githostarg=$(kvstore get gitfuncs_gitsvcs "$githost")
    else
        githostarg=''
    fi

    cat <<EOUSAGE
Usage: $cmd $githostarg upstream-namespace namespace repo
       Changes and adds appropriate entries in local git config such that the
       triangle workflow is set up between an upstream repo, your fork of that
       repo, and the current local clone of the fork. We also add our own entry
       that annotates the fact that we ran this function to accomplish all
       this.
EOUSAGE
}
