#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-in-a-worktree ()
{
    ##@@ 0001||group||git-in-a-worktree||Return 0 or 1, prints 'true' or 'false' if -p specified

    local print=$1;shift
    local v
    v=$(git rev-parse --is-inside-work-tree 2>/dev/null)
    local r=1
    [ "$v" = "true" ] && r=0
    [ "$print" = '-p' ] && echo "$v"
    return $r
}
