#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification:  Efficiency - in PS1>

git-get-default-remote ()
{
    # NO_SHIM
    local pre=$1;shift
    local post=$1;shift
    if git repo ina
    then
        local push_def
        push_def=$(git config --global push.default 2>/dev/null)
        if [ "$push_def" = 'simple' ]
        then
            local out
            out=$(git config --get remote."$(git config --get branch."$(git branch --show-current)".remote 2>/dev/null)".url 2>/dev/null)
            echo "${pre}${out}${post}"
        fi
    fi
}
