#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-logg ()
{
    ##@@ 0001||group||git-logg||

    git log --all --graph --pretty=format:'%Cred%h%Creset -%d %s (%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
}
