#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification:  Efficiency - in PS1>

git-get-default-remote ()
{
    # shellcheck disable=SC2034 #https://github.com/koalaman/shellcheck/wiki/SC2034
    local comment="<Function Justification:  Efficiency - in PS1>"
    local do_out='url'
    local -a cbargs
    if [[ $1 == -h ]] || [[ $1 == --help ]]; then
        git-usage git-get-default-remote
        return 0
    fi

    if [[ $1 == '--no-warn' ]]; then
        cbargs+=("$1"); shift
    fi

    if [[ $1 == --tag ]]; then
        do_out='tag'
        shift
    fi

    if [[ $1 == --host ]] || [[ $1 == --server ]]; then
        do_out='host'
        shift
    fi

    if [[ $1 == --namespace ]] || [[ $1 == --org ]]; then
        do_out='namespace'
        shift
    fi

    local pre=$1;shift
    local post=$1;shift

    if git repo ina; then
        if [[ "$(git config --global push.default 2>/dev/null)" = 'simple' ]]; then
            local current_branch
            current_branch=$(git repo current-branch "${cbargs[@]}")
            local tag
            tag=$(git config --get branch."$current_branch".remote 2>/dev/null)
            local out
            case $do_out in
                url)
                    out=$(git config --get remote."$tag".url 2>/dev/null)
                    ;;
                tag)
                    out="$tag"
                    ;;
                host)
                    out=$(git config --get remote."$tag".url 2>/dev/null | sed 's/:.*//')
                    ;;
                namespace)
                    out=$(git config --get remote."$tag".url 2>/dev/null | sed -e 's/.*://' -e 's/\/.*//')
                    ;;
            esac
            echo "${pre}${out}${post}"
        fi
    fi
}
autotrack git_get_default_remote "$0"
:<<'__PODUSAGE__'
=head1 NAME

git-get-default-remote - Return the default remote for the repo.

=head1 SYNOPSIS

 git-get-default-remote [ --no-warn ] [ --tag | [--host|-server ] | [ --namespace | -org ] ]
 git-get-default-remote [ --help ]

=head1 DESCRIPTION

Best described by example:

  ## The upstream remote if a fork, otherwise the origin
  $ git-get-default-remote
  ghe:someorg/somerepo

  ## Various information about the remote
  $ git-get-default-remote --tag
  upstream

  $ git-get-default-remote --host
  ghe

  $ git-get-default-remote --server
  ghe

  $ git-get-default-remote --namespace
  someorg

  $ git-get-default-remote --org
  someorg

B<--no-warn> is used in PS1 to prevent warning prints in repos that are in flux
between branches.

=cut

__PODUSAGE__
