#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: Efficiency - in PS1>

git-stash-get-count ()
{
    local no0=0; [[ "$1" = '-no0' ]] && no0=1 && shift;
    local pre=$1;shift
    local post=$1;shift
    if git repo ina; then
        local c
        c=$(git stash list 2>/dev/null | wc -l)
        ((c==0)) && ((no0)) && return
        echo "${pre}${c}${post}"
    fi
}
if ! $CRON; then
    if [[ -n $LOADED_git_stash_get_count ]]; then
        if [[ ! -f $0 ]]; then
            echo "--- loaded git-stash-get-count" >&2
        else
            echo "--- $(basename "$0") loaded git-stash-get-count" >&2
        fi
        export LOADED_git_stash_get_count=1
    fi
fi
