#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-diff-to-checkpoint ()
{
    ##@@ 0001||group||git-diff-to-checkpoint||Diff the current state of the local repo against the state as it was stored in git-pull-with-checkpoint

    local oldid=$(grep $(git-root).git-pull-checkpoint| head -1 | sed 's/commit//')
    local newid=$(git log -1 | head -1 | sed 's/commit//')
    git diff $oldid $newid
}
