#!/usr/bin/env bash

# <Function Class: git>

git-parse-remote-v ()
{
    gitfuncs_remotes=()
    declare remotes
    remotes=$( git remote -v | sed -r -e 's/\(.*//' -e 's/ +$//' -e 's/\t/=/' | sort -ru)
    [ -z "$remotes" ] && return 1
    for i in $remotes
    do
        key=${i%=*}
        value=${i#*=}
        # shellcheck disable=SC2034 # Set in env for later use.
        gitfuncs_remotes["$key"]="$value"
    done
    return 0
}
