#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-find-git-dir ()
{
    local dotgit
    dotgit=$(git root)/.git
    if [ -f "$dotgit" ]
    then
        ## Must be a worktree. Go find the source.
        dotgit="$(realpath "$(sed 's/gitdir: //' < "$dotgit")" | sed 's/.git\/.*/.git/')"
    fi
    if [ -d "$dotgit" ]
    then
        echo "$dotgit"
        return 0
    else
        echo
        return 1
    fi
}
