#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: none>

git-pull-with-checkpoint ()
{
    ##@@ 0001||group||git-pull-with-checkpoint||Write a file with the current UUID before pulling updates.

    git log -1 > "$(git root).git-pull-checkpoint"
    git pull "$@"
}
