#!/usr/bin/env bash

# <Function Class: gitfuncs.github>
# <Function Justification: none>

git-set-triangle-github ()
{
    ##@@ none||none||github-set-triangle||

    local usage_func="git-set-triangle-usage"
    [ -z "$1" ] && $usage_func ${FUNCNAME} github && return $NOT_OK

    git-set-triangle github "$@"
    return $?
}
