#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: cd>

# DO NOT REPLACE WITH AN ALIAS. The alias doesn't make it to subshells.

github-forknclone ()
{
    gitremote-forknclone github "$@"
}
