#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: cd>

github-forknclone ()
{

    if [ -z "$1" ] || [[ "$1" =~ -h ]]; then
        echo "usage: github-forknclone org repo [worktree]"
        echo "       Creates a fork of github:org/repo as github:$USER/repo"
        echo "       and then executes git clone --tree github:$USER/repo"
        exit 1
    fi

    declare -a forkof
    forkof=('--forkof' "$1")
    shift

    declare repo=$1;
    shift

    declare -a wt
    if [ -n "$1" ]; then
        declare -a wt
        wt=('--wt' "$1")
        shift
    fi

    git clone --tree "${forkof[@]}" "${wt[@]}" github:"$USER"/"$repo"
}
