#!/usr/bin/env bash

# <Function Class: git>
# <Function Justification: cd>

gitremote-clone ()
{
    local remote=$1; shift
    if [[ -z $1 ]] || [[ "$1" =~ -h ]]
    then
        echo "usage: ${FUNCNAME[2]} [options] [org repo | org/repo]"
        echo "       Clones the requested repo into the GITENV_REPO_ROOT ($GITENV_REPO_ROOT) tree."
        return 1
    fi

    local org
    local repo
    local -a args
    local lastarg="${*: -1}"
    if [[ "$lastarg" =~ / ]]
    then
        org="${lastarg%%/*}"
        repo="${lastarg##*/}"
        args=("${@:1:(($#-1))}")
    else
        org="${*: -2:1}"
        repo="${*: -1}"
        args=("${@:1:(($#-2))}")
    fi

    git clone "${args[@]}" --tree "$remote:$org/$repo"
}
