#!/usr/bin/env bash

# <Function Class: hist>
# <Function Justification: calls function that mods env>

history ()
{
    echo "$(date) history" >> ~/audithiststuff
    bash_history_sync
    builtin history "$@"
}
