#!/usr/bin/env bash

# <Function Class: hist>
# <Function Justification: none>

hist_with_pwd ()
{
    perl -an -e 'BEGIN{@out=()};
 if( $_ =~ m/^#([0-9]+)( ## pwd => (.*))*/ ) {
 push @out, {time=$1, pwd=$3};
 } else {
 $out[-1]->{cmd} = $_;
 }
 END {
 $idxfmt="%" . scalar(split(//,scalar(@out))) . "d";

 @out
 printf($idxfmt . ": %s %s %s",
         $., $_);' $HISTFILE
}
