#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: env mod>

hkeys ()
{
    ##@@ none||none||hvalues||Print all the keys of the hash named in arg1 to stdout, separated by a space. If the -list option is specified, then print each one on a separate line.

    local list=0
    if [ "$1" = '-list' ]
    then
        list=1
        shift;
    fi
    declare -n hash_alias="$1";shift
    if ((list))
    then
        for k in ${!hash_alias[@]}
        do
            echo $k
        done
    else
        echo ${!hash_alias[@]}
    fi
    return $?
}
