#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: none>

is-int ()
{
    ##@@ none||none||is-int||Is an integer. Return 0 if true.

    if [[ $1 =~ ^-?[0-9]+$ ]]
    then
        return 0
    else
        return 1
    fi

}
