#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: none>

is-pos ()
{
    ##@@ none||none||is-pos||Is an integer and is >= 0. Return 0 if true.

    is-neg "$1" && return "$NOT_OK"
    return "$OK"
}
