#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: none>

is_func_defined ()
{
    ##@@ none||none||is_func_defined||Is arg1 defined as a function. Returns 0 for no, 1 for yes.
    type "$1" 2>/dev/null | head -1 | grep -q 'is a function'
}
