#!/usr/bin/env bash

# <Function Class: hist>
# <Function Justification: env mod>

load_history ()
{
    echo "$(date) load_history" >> ~/audit-this-stuff
    local loadhist=$1
    if [ -z "$1" ]; then
        select loadhist in $(ls -rt "$HISTDIR")
        do
            if [ -n "$loadhist" ]; then
                break
            fi
        done
    fi
    if [ -n "$loadhist" ]; then
        loadhist="$HISTDIR"/$(basename "$loadhist")
        cat "$loadhist" >> "$HISTFILE"
    fi
}
