#!/usr/bin/env bash

# <Function Class: hist>
# <Function Justification: env mod>

new_history ()
{
    echo "$(date) new_history" >> ~/audit-this-stuff
    if [[ -z "$1" ]]; then
        echo "usage: new_history name"
        echo "       name should be just a filename."
        echo "       basename will be applied to it."
        echo "       It will be written in '$HISTDIR'."
        return
    else
        HISTFILE="$HISTDIR/$(basename "$1")"
    fi
    echo "Done"
}
