#!/usr/bin/env bash
###############################################################################
#
# Name:         pathfunc_usage
#
# Description:
#
# print a pathfunc_usage message
# $1 should be the script description
# $2..$n are additional information
#
# Author:      Stephen Collyer (scollyer@netspinner.co.uk)
#
# Copyright:   Netspinner Ltd 2000-2003
#
# <Function Class: path functions>
# <Function Justification: keep class members together>
###############################################################################

pathfunc_usage ()
{
    echo
    echo "pathfunc_usage: $1"
    echo
    shift
    declare i
    for i; do
        echo "    $i"
    done
    echo
}

# emacs
# Local Variables:
# mode: sh
# End:
