#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: maybe - frequency>

pause ()
{
    ##@@ none||none||pause||Print arguments as a prompt. Any keypress moves on.
    read -r -p "$@"
    return $?
}
