#!/usr/bin/env bash

# <Function Class: perl>
# <Function Justification: env mod>

perl-add-local()
{
    declare quiet=''
    [ "$1" == '-q' ] && quiet='-d'
    perl-add-root $quiet "${TILDAE:-$HOME}/local"
}
