#!/usr/bin/env bash

# <Function Class: perl>
# <Function Justification: env mod>

perl-add-root ()
{
    declare add_path_opt='-d'
    if [ "$1" == '-q' ]
    then
        add_path_opt='-D'
        shift
    fi

    local roottoadd=$1
    [ -z "$roottoadd" ] && roottoadd=${TILDAE:-$HOME}/perl
    roottoadd="$(realpath "$roottoadd")"

    ## Clean first in case they exist in the wrong order
    perl-del-root "$roottoadd"

    local pcv
    pcv=$(perl-current-version)
    ## Remember, the PERL5LIB mappings are listed in reverse order of how they
    ## need to appear.
    declare -a mappings
    mappings=(
        PERL5LIB:"$roottoadd/share/perl5/site_perl"
        PERL5LIB:"$roottoadd/share/perl5/site_perl/$pcv"
        PERL5LIB:"$roottoadd/lib/perl5"
        PERL5LIB:"$roottoadd/lib/perl5/site_perl"
        PERL5LIB:"$roottoadd/lib/perl5/site_perl/$pcv"
        PERL5LIB:"$roottoadd/lib64/perl5"
        PERL5LIB:"$roottoadd/lib64/perl5/site_perl"
        PERL5LIB:"$roottoadd/lib64/perl5/site_perl/$pcv"
        PATH:"$roottoadd/bin"
        MANPATH:"$roottoadd/man")
    for mapping in "${mappings[@]}"
    do
        envvar=${mapping%:*}
        value=${mapping#*:}
        addpath -x -f $add_path_opt -p "$envvar" "$value"
    done
}
