#!/usr/bin/env bash

# <Function Class: hist>
# <Function Justification: none>

rename_history ()
{
    if [ -z "$1" ]
    then
        echo usage: rename_history suffix
    else
        cp "$HISTFILE" "${HISTFILE}.$1"
        HISTFILE="${HISTFILE}.$1"
    fi
    echo "Done"
}
