#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: env mod>

safe_func_export ()
{
    [[ -z "$1" ]] && echo "usage: safe_func_export [funcname || --all]" && return 1;
    if [[ -n "$SHELL" ]] && [[ "$(basename "$SHELL")" = "bash" ]]; then
        local -a funcnames
        if [[ "$1" = '--file' ]]; then
            readarray -t funcnames < <(grep -E '^[a-zA-Z0-9_-]+\s*\(\)' "$2" | sed 's/\s*().*//')
        elif [[ "$1" = '--all' ]]; then
            readarray -t funcnames < <(declare -F | grep -v -- '-fx' | sed 's/declare -f//')
        else
            funcnames=("$@")
        fi
        # shellcheck disable=SC2163
        export -f "${funcnames[@]}"
    fi
}
autotrack safe_func_export "$0"
