#!/usr/bin/env bash

# <Function Class: dotfiles>
# <Function Justification: none>

showdotfiles ()
{
    # shellcheck disable=1090
    . "$DOTFILES_MANIFEST"

    echo foo
    # shellcheck disable=2154
    echo "${!dotfiles[@]}"
    for src in "${!dotfiles[@]}"
    do
        fullsrc="$DOTFILES_DIR/$src"
        link="${dotfiles[$src]}"
        echo
        echo "******"
        echo "$link"
        echo "******"
        ls -la "$link" "$fullsrc"
    done
}
