#!/usr/bin/env bash

# <Function Class: n/a>
# <Function Justification: env>

switch-ps1 () {
    if [[ -n $1 ]]
    then
        if [[ "$1" =~ -h ]]
        then
            bash-usage switch-ps1
            return
        fi
        declare ps1envar="PS1_${1^^}"
        if [[ -n "${!ps1envar}" ]]
        then
            export PS1="${!ps1envar}"
        else
            cmd-echo "'${ps1envar} not defined"
        fi
        return
    else
        declare ps1envar
        declare -a ps1envars
        readarray -t ps1envars < <(env | grep -E '^PS1_' | sed 's/=.*//'|sort)
        select ps1envar in "${ps1envars[@]}" 'quit'
        do
            [[ -z $ps1envar ]] && continue
            [[ $ps1envar != 'quit' ]] && export PS1=${!ps1envar}
            return
        done
    fi
}

return 0 ## POD guard

:<<'__PODUSAGE__'
=head1 NAME

switch-ps1 - choose between PS1 prompts

=head1 SYNOPSIS

 $ export PS1_SHORT='$ '
 $ export PS1_LONG='A very long PS1 $ '
 $ export PS1_SILLY=':-) $'

 $ switch-ps1 LONG
 A very long PS1 $ switch-ps1 SILLY
 :-) $ switch-ps1
 1) PS1_LONG
 2) PS1_SHORT
 3) PS1_SILLY
 4) quit
 #? 2
 $

=head1 DESCRIPTION

The synopsis says it all. Just define prompts in envars that start with 'PS1_'.

=cut

__PODUSAGE__
