#!/usr/bin/env bash

# <Function Class: xterm>
# <Function Justification: maybe - frequency>

termtitle ()
{
    if [[ $1 == '--pop' ]]; then
        /bin/echo -ne '\033[23;0t'  # Restore title from stack
        return
    fi

    if [[ $1 == '--push' ]]; then
        shift
        /bin/echo -ne '\033[22;0t'  # Save title on stack
    fi

    if (($#)); then
        echo -e "\\033]0;$*\\007\\c"
    fi
}
autotrack termtitle "$0"
