#!/usr/bin/env bash

# <Function Class: xterm>
# <Function Justification: isolate $$>

tickercfg ()
{
    local i=0
    local M
    local T
    local live=0
    if [[ "$1" == '--live' ]]
    then
        shift
        live=1
        M="::: $("$@") :::"
    else
        M="::: $* :::"
    fi
    T="$M$M$M$M"

    local f
    f="/tmp/ticker.$(hostname).$$"
    echo "$M" > "$f"

    local S ## First time around clears the prompt

    while sleep .2s && [ -r "$f" ]
    do
        settitle "$S"
        (( ++i>${#M} )) && i=1
        S=${T:i:40}
        if ((live))
        then
            M="::: $("$@") :::"
            T="$M$M$M$M"
            echo "$M" > "$f"
        fi
    done
}
