#!/usr/bin/env bash
###############################################################################
#
# Name:        uniqpath
#
# Author:      Matthew Persico (matthew.persico@gmail.com)
#
# Copyright:   Matthew Persico (matthew.persico@gmail.com)
#
# Derived from work by Stephen Collyer (scollyer@netspinner.co.uk),
#                      Copyright: Netspinner Ltd 2000-2003
#
# <Function Class: path functions>
# <Function Justification: env mod>
###############################################################################

uniqpath ()
{
    ###########################################################################
    # local variables
    ###########################################################################

    typeset options_shift_val options_missing_arg options_unknown_opt
    typeset options_num_args_left
    typeset opt_h opt_p opt_s
    typeset opt_x opt_v
    typeset sep=:

    typeset pathvar TEMP

    pathfunc_usage_init
    typeset -a USAGE
    i=0; USAGE[i]="uniqpath [-h] [-s separator] [-x] [-v] [[-p] pathvar] "
    ((i+=1)); USAGE[i]="Removes subsequent occurrances of path elements."
    ((i+=1)); USAGE[i]="$USAGE_OPT_P1"
    ((i+=1)); USAGE[i]="$USAGE_OPT_P2"
    ((i+=1)); USAGE[i]="$USAGE_OPT_P3"
    ((i+=1)); USAGE[i]="$USAGE_OPT_P4O"
    ((i+=1)); USAGE[i]="$USAGE_OPT_P5"
    ((i+=1)); USAGE[i]="$USAGE_OPT_S"
    ((i+=1)); USAGE[i]="$USAGE_OPT_X"
    ((i+=1)); USAGE[i]="$USAGE_OPT_V"
    ((i+=1)); USAGE[i]="$USAGE_OPT_H"

    ###########################################################################
    # handle options
    ###########################################################################

    options "hp:s:xv" "$@"
    shift "$options_shift_val"

    if [ -n "$opt_h" ]; then
        Usage "${USAGE[@]}"
        return
    fi
    if [ -n "$options_missing_arg" ]; then
        Usage "${USAGE[@]}" "Missing argument for -$options_missing_arg"
        return
    fi
    if [ -n "$options_unknown_opt" ]; then
        Usage "${USAGE[@]}" "Unknown option -$options_unknown_opt"
        return
    fi
    if [ "$options_num_args_left" -eq 1 ]; then
        pathvar=$1
    fi

    [ -n "$opt_s" ] && sep=$opt_s;
    [ -n "$opt_p" ] && pathvar=$opt_p # use specified pathvar
    [ -z "$pathvar" ] && pathvar=PATH  # default

    ###########################################################################
    # main
    ###########################################################################

    # Long path variable values may overflow arg list limits on some Unices. It
    # is also difficult, in a series of pipes, to deal with paths that have
    # spaces in them . Therefore we use an intermediate file.

    TEMP=/tmp/uniqpath.out.$$
    listpath -s "${sep}" -p $pathvar | awk '{seen[$0]++; if (seen[$0]==1){print}}' > $TEMP
    local newvalue
    local line
    while read -r line
    do
        [ -n "$newvalue" ] \
            && newvalue="${newvalue}${sep}${line}" \
                || newvalue="${line}"
    done < $TEMP
    eval $pathvar="'$newvalue'"
    /bin/rm -f $TEMP
    [ -n "$opt_v" ] && listpath -s "${sep}" -p $pathvar
    # shellcheck disable=SC2163
    [ -n "$opt_x" ] && export $pathvar

}

# emacs
# Local Variables:
# mode: sh
# End:
