#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: env>

# Allows you to call unset on the export statement.

unsete ()
{
    declare i
    declare ii
    for i in "$@"; do
        ii=${i%%=*}
        builtin unset "$ii"
    done
}
