#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: env>

# Allows you to call unset on the export statement.

unset ()
{
    for i in "$@"
    do
        ii=${i%%=*}
        builtin unset "$ii"
    done
}
