#!/usr/bin/env bash

# <Function Class: cd>
# <Function Justification: change cwd>

up ()
{
    local tgt=$1
    if [ -z "$tgt" ]
    then
        tgt=1
    fi

	if is-int "$tgt"
	then
        if is-neg "$tgt"
	    then
            stderrcho 'up takes positive numbers. We will convert for you.'
        else
            ((tgt=tgt*-1))
        fi
        dirlist $tgt
    else
        stderrcho 'up takes positive numbers.'
    fi
}
