#!/usr/bin/env bash

# <Function Class: util>
# <Function Justification: none>

wcstrip ()
{
    # shellcheck disable=2034
    local -a wcstriplist
    asplit wcstriplist ' ' "$(wc "$@" )"
    apop wcstriplist > /dev/null
    avalues wcstriplist
}
