#!/usr/bin/env bash

# <Function Class: X>
# <Function Justification: none>

x-current-root-guts ()
{
    x-is-available;
    if [ ! "$?" = "${TRUE}" ]
    then
        return "$FALSE"
    fi
    xwininfo -root | grep -i "$1:" | sed 's/.* //'
    return "$TRUE"
}
