#!/usr/bin/env bash

# <Function Class: X>
# <Function Justification: none>

x-current-root-guts ()
{
    if x-is-available
    then
        return 1
    fi
    xwininfo -root | grep -i "$1:" | sed 's/.* //'
    return 0
}
