#!/usr/bin/env bash

# <Function Class: X>
# <Function Justification: none>

x-is-available ()
{
    if [ -z "$XFUNCS_X_IS_AVAILABLE" ]
    then
        (xrandr || xwininfo || false ) >/dev/null 2>&1
        XFUNCS_X_IS_AVAILABLE=$?
        export XFUNCS_X_IS_AVAILABLE
    fi
    return $XFUNCS_X_IS_AVAILABLE
}
