#!/usr/bin/env bash
git grep -l -E '.' | \
    grep -v '/fontconfig/' | \
    grep -v '/fonts/' | \
    grep -v '/Tk' | \
    grep -v '/man/' \
         > critical.manifest

cat critical.manifest | \
    grep -v bin/.bcpcvms | \
    grep -v bin/snapshotfuncs | \
    grep -v bin/svnfuncs | \
    grep -v bin/tkmore | \
    grep -v bin/tkpod | \
    grep -v bin/toolkit-login | \
    grep -v bin/vmfuncs | \
    grep -v bin/vmrsync.cron | \
    grep -v bin/yumaptfuncs | \
    grep -v dotfiles/Xdefaults | \
    grep -v dotfiles/config/git/gitk | \
    grep -v dotfiles/config/gtk-3.0/settings.ini | \
    grep -v dotfiles/config/hub | \
    grep -v dotfiles/config/pudb/pudb.cfg | \
    grep -v dotfiles/ssh.config.bbgithub.all | \
    grep -v dotfiles/ssh.config.devgit.vm | \
    grep -v dotfiles/ssh.config.localhost.vm | \
    grep -v dotfiles/xterminit \
         > critical-cygwin.manifest
