#!/usr/bin/env/bash

# shellcheck disable=SC2046 #https://github.com/koalaman/shellcheck/wiki/SC2046
# shellcheck disable=SC2009 #https://github.com/koalaman/shellcheck/wiki/SC2009
kill $(ps -o etime,pid,command -U "$USER" \
           | grep dbus-daemon | grep -v grep \
           | sort | perl -ane 'print qq($F[1] ) if $F[0] =~ m/^\d+-/')
